mapillary/mapillary_tools

python/README.md
python/lib_gps_exif.py
python/remove_duplicates.py

I mostly map using an action cam, that takes an image e.g. once each second. When crossing streets I need to remove a lot of images and when going slow once a second produces too many images. Further more the cameras GPS has manged to put my first images in Russia, when I was in Denmark, creating some very long lines on the world map (thanks to Peter Neubauer for pointing it out).
This caused me to write this script:
* Images too close are moved to a duplicate folder. Parameters for distance and panning can be given.
* Images with unrealistic high speeds are moved to an error folder. Speed is both taken from EXIF and calculated between images. It also suggests if time_split.py should be run.
The script uses PIL/Pillow instead of exif_read, like the other scripts. The reason is, that …

Removal of duplicate images

---

python/lib_gps_exif.py
python/remove_duplicates.py

New
* Images are now sorted by creation time as e.g. time_split.
Bugfix
* Images without a proper orientation tag can now be duplicates too.
* Image resources are closed properly.
Note
Sorting by creation time is done at least 20-30 times faster by this script than the same operation is done by e.g. time_split.py. The reason is that this script uses PIL/Pillow which is much faster than exif_read.
In lib_gps_exif.py, in the class PILExifReader now have the method read_capture_time which works exactly like its counterpart in time_split.py, except that it is much much faster.
See remove_duplicates.pyline 243 for a 3 line example on how it can be used.
The only issue with this method is that some times PIL or Pillow is harder to install. PIL is the original Python image library but is not …

Bugfixes and sorting

---

python/requirements.txt

Fix following error for me:
```
Traceback (most recent call last):
File "mapillary_tools/python/geotag_from_gpx.py", line 11, in <module>
from dateutil.tz import tzlocal
ImportError: No module named dateutil.tz
```

Fix import error for dateutil.tz

---

python/geotag_from_gpx.py
python/requirements.txt

It wasn't being used anywhere in the code. In addition, matplotlib depends
on numpy, which has native-code parts, and was making pip tell Windows
users to install Visual C++.

Remove unnecessary matplotlib dependency.

---

python/geotag_from_gpx.py

gpxpy isn't commonly packaged, and is only used by one function. Before, it was needed to run interpolate_direction.py even though it wasn't used by it

Don't fail if gpxpy isn't needed and can't be loaded

---

python/geotag_from_gpx.py

The list coming from os.walk is in an arbitrary order but the sub-second timing function needs the list of files to be ordered.
I kept getting the ```Interval not compatible with EXIF times``` error message on a sequence that seemed like it should be working. It turns out ```smin``` and ```smax``` in the sub-second timing function were being initialized from some random picture in the middle of the sequence and things went crazy from there.
This does rely on file name sorting and assumes this matches the order in which the photos were taken but I feel like for action cameras this is a pretty safe bet.

Make file ordering explicit

---

python/lib/exifedit.py
python/upload_with_preprocessing.py

re #127 
This lets the bulk uploader accept an `offset_angle` parameter for side/rear-facing cameras.
I'm still seeing some mysterious orientation flips though, so not sure if there is something broken in the `normalize_bearing` code.
Supposed to be rear-facing:
Supposed to be right-facing:

Add offset_angle parameter for upload_with_preprocessing.py

---

python/geotag_from_gpx.py

This allows the handling of cameras that are reversed or off-center  from the direction of travel.
Note the check for < 0 but no check for > 360. Apparently exiv handles > 360 without complaining but it threw errors for any negative degrees.

New option to spcify camera bearing

---

python/add_fix_dates.py

This allows `time_offset` in `add_fix_dates.py` to be provided in floating point rather than integer seconds.   (for example, in case you are extracting from a timelapse sequence with frames at half second intervals.)

Allow time_offset to be specified in floating point seconds

---

python/upload_video_with_preprocessing.py

The way the command is built and executed in `upload_video_with_preprocessing.py` results in an error when project name contains whitespace. The solution is to add quotes to project name.

Support for projects with whitespace in the name in video upload

---

python/lib/ffprobe.py

The video metadata parsing in `ffprobe.py` assumes the lines returned from `ffprobe -show_streams` are always in the format of `key=value`. However for some videos, this may not be true. As a result, the script crashes.
Here's a sample output from video captured with Garmin VIRB XE:
```
[STREAM]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
...more properties here...
TAG:language=eng
TAG:handler_name=
Garmin AVC
TAG:encoder=Garmin AVC encoder
[/STREAM]
```
The `TAG:handler_name` property value starts with newline for some reason.
Te solution suggested in this PR is to ignore the lines in incorrect format (but print a warning).

Ignore video metadata in incorrect format

---

python/remove_duplicates.py

os.rename() doesn't work when moving files between different devices. It
will lead to OSError: [Errno 18] Cross-device link. Use shutil.move()
instead.
Fixes #154

remove_duplicates: Fix move between different devices #154

---

python/lib/uploader.py

Failing to do this causes me to run out of file descriptors when using
my new 300 MBit line to upload. I guess my old ADSL was so slow that enough connections timed out.

Closing network connection after use.

---

python/geotag_video.py

Reading the video creation time was already intended, but the function was not actually used.
Also, I added another datetime format to try, as it was what my Sony camera produced.
Also, added some clarification for the time offset parameter in its description.

Get video creation time from the video itself

---

python/lib/exifedit.py

Rely on piexif to properly save image on all platforms (need to use file access binary write).

Simplify ExifEdit.write()

---

mapillary_tools/exif_read.py

If a jpg file contains a SubSecTimeOriginal field with a value of 0.000005, the extract_capture_time method returns a microsecond value of 500000 instead of 5
this commit correct this bug

bugfix: extract_capture_time return a wrong microsecond value

---

.gitignore
mapillary_tools.spec
script/build

Add `script/build` to build a standalone `mapillary_tools` binary
Reference issue: https://github.com/mapillary/mapillary_elva/issues/5360

feat: add build script for pyinstaller

---

mapillary_tools.spec
pyinstaller/hooks/hook-urllib2.py
pyinstaller/runtime-hooks/ssl.py

@sbaldassin @jernejaMislej We need to add `pip install certifi` to the build script but only for OSX
Reference issue: mapillary/mapillary_elva#5420

feat: add SSL support for OSX

---

mapillary_tools/processing.py
mapillary_tools/uploader.py
mapillary_tools/utils.py

Related to https://github.com/mapillary/mapillary_elva/issues/6624
Required for https://github.com/mapillary/mapillary_tools_for_desktop/pull/36

fix: ipc encoding on Windows for import paths encoded as cp1252

---

mapillary_tools/processing.py

Note that this will cause Mapillary to no longer find the files from
previous runs.
Signed-off-by: Francois Gouget <fgouget@free.fr>

Fix spelling in the processed images mapillary path

---

README.md
mapillary_tools/commands/download.py
mapillary_tools/download_blurred.py

This PR updates how the download blurred originals command works, it relies on the APIs I built recently. These are the changes:
- An admin **can download any image**, whether private/public which belongs to an organization
- A member **can download any image**, whether private/public which belongs to an organization
- A contributor **cannot** download any images whether private/public which belongs to an organization
These changes are mostly cosmetic and don't effectively change the previous behavior, besides extending it by `--private` flag which now accepts `false` so the organization user has a chance to download publicly uploaded organization imagery.
I've updated the README, please let know if this makes sense @katrinhumal.

feat: allow scoped organization downloads

---

mapillary_structure.json
mapillary_tools/edit_config.py
mapillary_tools/process_upload_params.py
mapillary_tools/processing.py
mapillary_tools/uploader.py
script/run
tests/integration/mapillary_tools_process_images_provider/setup
tests/integration/mapillary_tools_process_images_provider/test_process_images_provider.py

Fixes the hardcoded AWS key by using the AWS key provided by the upload API
@jernejaMislej @ybkuang Could you also review these lines too?
https://github.com/mapillary/mapillary_tools/pull/360/files#diff-d16f9199f43eb8f153ddfc6f204f95afR41-R42
I'm not sure how common is to trigger this flow `uploader.upload_file_list_direct(...)`
Also, the `UPLOAD_PARAMS` has a hardcoded policy that expired in 2020-01-01

Feat dynamic aws key

---

mapillary_tools/edit_config.py

Currently, when you manually provide `--user_name`, `--user_password`, `--user_email` in `edit_config()` in `edit_config.py`, you get an unpacking error: `ValueError: too many values to unpack`
It turns out that it's missing the `aws_access_key_id` return value from `get_user_key()` (from `uploader.py`) when unpacking.
Both `prompt_user_for_user_items()` and `authenticate_with_email_and_pwd()` from `uploader.py` have this fix.

quick fix: Add aws hash unpack in edit_config.py.

---

mapillary_tools/process_csv.py

Fixes https://github.com/mapillary/mapillary_tools/issues/399

fix process_csv

---

mapillary_tools/camera_support/prepare_blackvue_videos.py
mapillary_tools/gpx_from_blackvue.py
mapillary_tools/processing.py

Fixes https://github.com/mapillary/mapillary_tools/issues/394

Fix JSON serialization in blackvue processing

---

mapillary_tools/processing.py

For some reason tools can't extract GPS data from some blackvue videos, we should skip these videos instead of stop the whole process.
Fixes https://github.com/mapillary/mapillary_tools/issues/394

skip blackvue video that has no GPS data found

---

mapillary_tools/upload.py
mapillary_tools/uploader.py

https://github.com/mapillary/mapillary_tools/issues/450
Before wrote history right after upload is done, now write history after both upload and finish_upload API are done.

Write upload history after finish_upload is done

---

.github/workflows/python-package.yml
README.md
setup.py

1. fixed the wrong module path
2. test pip installation integration tests﻿

fix: wrong module path in setup.py

---

mapillary_tools/api_v4.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
requirements.txt

The default timeout for requests is None, which will wait forever.
This PR sets the upload timeout to 10 minutes, and the other request timeouts to 1 minute.
- fix: add timeouts for all HTTP requests
- Simplify retryable error messages

fix: set timeout for requests

---

mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py

When fetch_offset failed, it's possible to read an unexisting key from the progress dict. This PR fixes that.

fix: the possible KeyError when fetch offset failed

---

README.md
mapillary_tools/commands/__main__.py
mapillary_tools/commands/upload_blackvue.py
mapillary_tools/commands/upload_zip.py
mapillary_tools/commands/zip.py
mapillary_tools/geotag/geotag_from_blackvue.py
mapillary_tools/upload.py
mapillary_tools/uploader.py
mapillary_tools/utils.py
tests/integration/test_process.py

The current "upload" command handle many cases and it is getting complicated:
```
- upload video1.mp4 video2.mp4
- upload mly_tools_xxx.zip mly_tools_yyy.zip
- upload image_folder1 image_folder2
```
When it comes to uploading a folder, "upload" doesn't know if it's a folder of images or a folder of blackvues.
This PR adds two separate commands "upload_blackvue" and "upload_zip", while let "upload" focus on uploading a single directory of images:
```
- upload_blackvue blackvue_folder blackvue.mp4
- upload_zip zip_folder mly_tools_xxx.zip
- upload image_dir
```

feat: add commands for uploading blackvue/zip directories

---

.github/workflows/python-package.yml
mapillary_tools/geotag/geotag_from_gopro.py
tests/integration/mapillary_tools_process_images_provider/data/README
tests/integration/mapillary_tools_process_images_provider/gopro_data/README
tests/integration/test_gopro.py

Fixes https://github.com/mapillary/mapillary_tools/issues/503

fix: subprocess processing temporary file in Windows

---

.github/workflows/python-package.yml

This makes the change to GH action to use 32bit Python when building the executables in order to be compatible with 32bit Windows.

feat: Use 32bit Python

---

mapillary_tools/geotag/simple_mp4_parser.py

The sample size could be non-zero. In this case all samples have the same size.

fix: parsing stsz box

---

mapillary_tools/geotag/simple_mp4_parser.py
tests/unit/test_simple_mp4_builder.py

`sample.description_idx` should be always 1-based (same as the one parsed from `stsc`).

fix: off-by-one error in sbtl parsing

---

mapillary_tools/geotag/simple_mp4_builder.py
mapillary_tools/geotag/simple_mp4_parser.py
tests/cli/simple_mp4_builder.py
tests/unit/test_simple_mp4_builder.py

Need the CLI to test mp4 decoding and encoding.
Usage:
```
python3 -m tests.cli.simple_mp4_builder in.mp4 out.mp4
```
`out.mp4` should be a valid and playable mp4 with video tracks only.
Add CAMM during the transform is the next thing.

feat: add a test CLI that transforms mp4 to mp4

---

mapillary_tools/commands/__main__.py
mapillary_tools/commands/process.py
mapillary_tools/commands/process_and_upload.py
mapillary_tools/commands/sample_video.py
mapillary_tools/commands/upload.py
mapillary_tools/commands/upload_blackvue.py
mapillary_tools/commands/upload_camm.py
mapillary_tools/commands/upload_zip.py
mapillary_tools/commands/video_process_and_upload.py
mapillary_tools/geotag/geotag_from_blackvue.py
mapillary_tools/geotag/geotag_from_camm.py
mapillary_tools/geotag/geotag_from_exif.py
mapillary_tools/geotag/geotag_from_gopro.py
mapillary_tools/geotag/geotag_from_gpx.py
mapillary_tools/geotag/geotag_from_gpx_file.py
mapillary_tools/geotag/geotag_from_nmea_file.py
mapillary_tools/geotag/gpmf_parser.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/process_import_meta_properties.py
mapillary_tools/process_sequence_properties.py
mapillary_tools/sample_video.py
mapillary_tools/types.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
mapillary_tools/utils.py
tests/integration/test_gopro.py
tests/integration/test_process.py
tests/unit/test_utils.py

- Support multiple import paths for process/upload/process_and_upload: `process/upload/process_and_upload folder1/ folder2/ image.jpg`
- `process_upload` and `video_process_upload` won't generate `mapillary_image_description.json` by default unless you specify it with `--desc_path`
- The "filename" property in `mapillary_image_description.json` are full path instead of relative path to the import path. For example `"hello/world.jpg"` in the import path `~/images` becomes `"~/images/hello/world.jpg"` now.
- When multiple import paths are specified, users have to specify `--desc_path` otherwise it has no idea where to write `mapillary_image_description.json`

feat: support multiple import paths

---

mapillary_tools/geotag/camm_builder.py
mapillary_tools/geotag/io_utils.py
mapillary_tools/geotag/simple_mp4_builder.py
mapillary_tools/process_import_meta_properties.py
tests/integration/test_gopro.py
tests/unit/test_camm_parser.py
tests/unit/test_io_utils.py

- add chainedIO and slicedIO
- use io_utils in transform_mp4

feat: streamable mp4 transform

---

mapillary_tools/commands/upload.py
mapillary_tools/commands/upload_blackvue.py
mapillary_tools/commands/upload_camm.py
mapillary_tools/commands/upload_zip.py
mapillary_tools/geotag/camm_builder.py
mapillary_tools/geotag/geotag_from_camm.py
mapillary_tools/geotag/geotag_from_exif.py
mapillary_tools/upload.py
mapillary_tools/uploader.py
mapillary_tools/utils.py
setup.py

Add `--file_types` that allows on-the-fly CAMM conversion from other video formats:
```
mapillary_tools upload --file_types=blackvue,gopro,camm,image ~/MapillaryUploadData/ --dry_run
```

feat: add on-the-fly CAMM video conversion to the upload command

---

mapillary_tools/process_sequence_properties.py
tests/cli/process_sequence_properties.py
tests/unit/test_sequence_processing.py

- fix: capture time ordering for sequence processing
- rename
Fixes https://github.com/mapillary/mapillary_tools/issues/551

fix sequence processing order

---

mapillary_tools/exif_read.py

fixes https://github.com/mapillary/mapillary_tools/issues/555

fix: skip empty EXIF values

---

.github/workflows/python-package.yml
mapillary_tools/process_sequence_properties.py
tests/cli/process_sequence_properties.py
tests/integration/test_process.py
tests/unit/test_sequence_processing.py

- fix sequence processing order (#553)
- apply group_and_sort_descs_by_folder

fix: sequence processing order for v0.8

---

mapillary_tools/sample_video.py

Fix:
```
ValueError: 'mapillary_public_uploads/xxx.mp4' is not in the subpath of '/Users/taopeng/mapillary_tools/mapillary_public_uploads' OR one path is relative and the other is absolute.
```

fix: resolve video path

---

.github/workflows/python-package.yml

Fixes https://github.com/mapillary/mapillary_tools/issues/566

CI: install pysocks when building binaries

---

mapillary_tools/constants.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
tests/cli/upload_api_v4.py
tests/unit/test_uploader.py

Fixes https://github.com/mapillary/mapillary_tools/issues/570
The upload chunk size affects the upload speed. Here is a rough upload speed comparison with different chunk sizes under the same network configuration:
```
❯ python3 -m tests.cli.upload_api_v4 empty_data foo16 --chunk_size=5
0%|▏                           | 35.0M/29.0G [00:06<1:22:52, 6.26MB/s]
```
```
❯ python3 -m tests.cli.upload_api_v4 empty_data foo16 --chunk_size=16
0%|▎                         | 80.0M/29.0G [00:08<50:45, 10.2MB/s]
```
```
❯ python3 -m tests.cli.upload_api_v4 empty_data foo16 --chunk_size=32
1%|█                         | 250M/29.0G [00:04<38:43, 13.3MB/s]
```
This PR changes the default chunk size to 16MB and allows users to customize it with `MAPILLARY_TOOLS_UPLOAD_CHUNK_SIZE_MB`, an example:
```
❯ …
```

improve: increase upload chunk size to 16MB

---

mapillary_tools/authenticate.py
mapillary_tools/constants.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
tests/cli/upload_api_v4.py

- retry immediately for HTTP 412
- add envvar `MAPILLARY_TOOLS_MAX_UPLOAD_RETRIES` to control number of retries
- remove wrap_http_exception from authenticate.py
https://github.com/mapillary/mapillary_tools/issues/569

fix: immediate reties on HTTP 412

---

mapillary_tools/geotag/camm_builder.py
mapillary_tools/geotag/construct_mp4_parser.py
mapillary_tools/geotag/mp4_sample_parser.py
mapillary_tools/geotag/simple_mp4_builder.py
mapillary_tools/sample_video.py
mapillary_tools/uploader.py
tests/cli/simple_mp4_parser.py
tests/unit/test_simple_mp4_builder.py

According to mp4 spec this ctts box is required if there exists bframes, without this box, the generated mp4 will be jumping back and forth as follows.
Also ctts, if present, is the table for sorting out frame presentation ordering.
sample-5s.mp4
https://user-images.githubusercontent.com/87357/204927246-f8dce529-db49-4f52-903d-e4372eec6435.mp4
- use contextmanager
- add CompositionTimeToSampleBox (ctts)
- move find_box_at_pathx to construct_mp4_parser.py
- fix: parse ctts

fix: parse and build ctts (Composition Time to Sample Box)

---

mapillary_tools/commands/video_process.py
mapillary_tools/sample_video.py

Raise the error if non-exif geotag source is specified with the distance-based sampling
```
ERROR   - MapillaryBadParameterError: Geotagging from "gpx" works with the legacy interval-based sampling only.
To switch back, rerun the command with "--video_sample_distance -1 --video_sample_interval 2"
```
Fixes https://github.com/mapillary/mapillary_tools/issues/596

fix: stop video sampling if non-exif geotag source provided

---

mapillary_tools/exif_read.py
mapillary_tools/geotag/geotag_from_exif.py
mapillary_tools/geotag/geotag_from_gpx.py
mapillary_tools/geotag/geotag_from_video.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/sample_video.py
mapillary_tools/types.py
tests/integration/test_process.py
tests/integration/test_process_and_upload.py

- make sure exif reading do not fail
- multiprocessing geotag_from_exif
- multiprocessing geotag_from_gpx
- move process_video to geotag_from_video

feat: process images/videos in parallel with multiprocessing

---

mapillary_tools/sample_video.py

This fix will attempt to rename the temporary folder for 10sec. This is due to an issue on windows machines that causes the renaming of the temporary folder to result in a PermissionError for several seconds after the last image is written.

wip_dir Context Manager Rename Retry

---

README.md

Installation without libexpat failed with
```
ImportError: dlopen failed: library "libexpat.so.1" not found: needed by /data/data/com.termux/files/usr/lib/python3.11/lib-dynload/pyexpat.cpython-311.so in namespace (default)
```

Mention libexpat as dependency for Termux

---

mapillary_tools/exif_write.py

Fixes https://github.com/mapillary/mapillary_tools/issues/662

fix DNG image processing

---

.github/workflows/release.yml

This change will enable us to make a mapillary_tools osx-x86_64 build again.

Update macOS version in release.yml

---

requirements-dev.txt

This updates the Pillow (used in unit tests) to the latest version due to security vulnerabilities in the old one.
It installs version 10.4.0 now and tests are passing:

Update Pillow to latest version

---

.github/workflows/release.yml
requirements.txt

- **Support pysocks by default**
- **remove pysocks installation from the release action**

Support socks proxy

---

.github/workflows/python-package.yml
mapillary_tools/mp4/mp4_sample_parser.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/sample_video.py
mapillary_tools/video_data_extraction/extractors/base_parser.py
mapillary_tools/video_data_extraction/extractors/camm_parser.py
mapillary_tools/video_data_extraction/extractors/gpx_parser.py
requirements-dev.txt
tests/unit/test_sequence_processing.py

- **ruff check mapillary_tools --fix**
- **ruff format mapillary_tools tests**
- **update the CI**

CI: replace flake/black with ruff

---

mapillary_tools/geotag/gpmf_parser.py
mapillary_tools/imu.py
tests/cli/gpmf_parser.py

This pull request introduces significant changes to the `mapillary_tools/geotag/gpmf_parser.py` file, focusing on enhancing telemetry data extraction and handling. The most important changes include the addition of new functions for matrix calibration and telemetry data extraction, as well as updates to existing functions to accommodate these enhancements.
Enhancements to telemetry data extraction:
* [`mapillary_tools/geotag/gpmf_parser.py`](diffhunk://#diff-b41dfe7c0ca31c400ed96c48f8823ba61b7a4d76c7b61d563e194d633551852dR311-R424): Added new functions `_is_matrix_calibration`, `_build_matrix`, `_apply_matrix`, `_flatten`, `_get_matrix`, `_scale_and_calibrate`, `_find_first_telemetry_stream`, and `extract_telemetry_data` to support telemetry data extraction and processing. …

feat: extract IMU from GoPro videos

---

mapillary_tools/geotag/gpmf_parser.py

This pull request introduces several improvements to the `mapillary_tools/geotag/gpmf_parser.py` file, focusing on enhancing GPS timestamp handling and code organization. The most important changes include reordering imports, adding error handling for GPS timestamp conversion, implementing a function to backfill GPS timestamps, and modifying the extraction of points from samples to use the new backfill function.
Enhancements to GPS timestamp handling:
* Added error handling in the `gps5_from_stream` function to ensure robustness when converting GPS timestamps.
* Implemented a new function `_backfill_gps_timestamps` to fill in missing GPS timestamps based on available data points.
* Modified the `_extract_points_from_samples` function to use the `_backfill_gps_timestamps` function, …

fix: interpolate invalid GPS timestamps

---

requirements-dev.txt
requirements.txt
tests/unit/test_exifedit.py
tests/unit/test_exifread.py

This pull request focuses on refactoring the unit tests for EXIF data handling by removing dependencies on the `Pillow` library and utilizing the `ExifRead` class for reading EXIF data. The main changes include the removal of `Pillow` from the requirements and test files, and the replacement of `Pillow`-based EXIF reading methods with methods from the `ExifRead` class.
Key changes include:
* [`requirements-dev.txt`](diffhunk://#diff-2b4945591edfeaa4cf4d3f155e66d4b43d1bda7a55d881d5cf3107f1b05abbbcL1): Removed `Pillow` from the list of dependencies.
* [`tests/unit/test_exifedit.py`](diffhunk://#diff-1161b74f3ede391b5edbe269d2909ef2b44efde50bda52a3e9ab167247d09c70R9-L10): Removed `Pillow` imports and related EXIF reading methods, replacing them with `ExifRead` class methods. …

chore: remove Pillow from dev dependency

---

mapillary_tools/api_v4.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py

MLY tools may fail in SSL verification some corporate proxy. This PR try using the system SSL certs if it fails using the SSL certs provided by certifi.
```
2025-01-23 22:13:59,152 - WARNING - SSL error occurred, falling back to system SSL certificates: HTTPSConnectionPool(host='graph.mapillary.com', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)')))
```

fix: fallback to system SSL certs when certifi fails

---

mapillary_tools/constants.py

This pull request includes changes to the `mapillary_tools/constants.py` file, specifically modifying the environment variable defaults for sequence limits.
Changes to sequence limits:
* [`mapillary_tools/constants.py`](diffhunk://#diff-9ff8ceb711e986920337274ad817fcd4e87b7648be7e59189de5f3722bafc7feL46-R48): Increased the default `MAX_SEQUENCE_LENGTH` from 500 to 1000.
* [`mapillary_tools/constants.py`](diffhunk://#diff-9ff8ceb711e986920337274ad817fcd4e87b7648be7e59189de5f3722bafc7feL46-R48): Increased the default `MAX_SEQUENCE_FILESIZE` from 2G to 10G.

chore: increase sequence limit to 1000 images

---

pyinstaller/hooks/hook-urllib2.py
pyinstaller/runtime-hooks/ssl.py

pyinstaller does include all certifi cacerts in the bundle, so there is no need to do it again

remove SSL hooks in pyinstaller

---

mapillary_tools/camm/camm_builder.py
mapillary_tools/camm/camm_parser.py
mapillary_tools/geotag/geotag_videos_from_exiftool_video.py
mapillary_tools/geotag/geotag_videos_from_video.py
mapillary_tools/video_data_extraction/extract_video_data.py
mapillary_tools/video_data_extraction/extractors/base_parser.py
mapillary_tools/video_data_extraction/extractors/exiftool_xml_parser.py
mapillary_tools/video_data_extraction/extractors/gpx_parser.py

When we found GPS timestamps videos (e.g. GoPro or CAMM), we will use the first GPS timestamp to synchronize GPX tracks. NOTE we have to assume the timestamps in GPX are also using the GPS clock.

feat: sync GPX with first GPS timestamp when available

---

mapillary_tools/geotag/geotag_images_from_gpx_file.py
mapillary_tools/video_data_extraction/extractors/gpx_parser.py

A more explicit error when GPX parsing fails:
```
[
{
"error": {
"type": "RuntimeError",
"message": "Error parsing GPX /usr/xx/Downloads/Forward.gpx: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte"
},
"filename": "/usr/xx/Downloads/Forward.mp4",
"filetype": "video"
}
]

improve GPX parsing error message

---

mapillary_tools/video_data_extraction/extractors/camm_parser.py
mapillary_tools/video_data_extraction/extractors/gpx_parser.py

Problem is when run:
```
mapillary_tools process --video_geotag_source '{"source":"gpx","pattern":"/external_gpx/%g.gpx"}' ~/Downloads/video\ full.360
```
will throw this exception (warning) and skip gpx geotagging:
```
Exception for parser gpx while processing source /external_gpx/video full.gpx: "unable find box at path [b'moov']"
```

fix: enforce camera info to be extracted from video itself instead of gpx

---

mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
tests/unit/test_upload_api_v4.py

When upload a large file, we slice the large binary stream into chunks (16MB per chunk by default -- can be specified by `MAPILLARY_TOOLS_UPLOAD_CHUNK_SIZE_MB`), and then upload each chunk to the server per HTTP request. It means to upload a 16GB file, it will send over 1000 HTTP requests.
I suspect that many potential issues are caused by initializing HTTP requests instead of the actual data transferring after the initialization, especially in an unreliable and dynamic network environment. To address these issues, we are switching to [Chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) that the upload server supports.
To upload a 16GB file, we still slice it into chunks by 16MB, but within **a single HTTP request**. This is what [Chunked transfer …

improve: use chunked transfer encoding to stream large files

---

mapillary_tools/exif_read.py
mapillary_tools/geotag/geotag_images_from_exif.py
mapillary_tools/geotag/geotag_images_from_exiftool.py
mapillary_tools/process_geotag_properties.py
tests/integration/fixtures.py
tests/integration/test_history.py
tests/unit/test_sequence_processing.py

- **disable metadata validation and upload status in process stage**
- **turn off detials and debug flags in exifread.process_file**
- **improve exif extraction**
Before: processing 9852 images
```
uv run -m mapillary_tools.commands process  --desc_path /tmp/foo.json   66.19s user 8.62s system 515% cpu 14.508 total
```
After: processing 9852 images (without validation)
```
uv run -m mapillary_tools.commands process  --desc_path /tmp/foo.json   5.98s user 2.37s system 238% cpu 3.494 total
```
After: processing 9852 images (with validation)
```
uv run -m mapillary_tools.commands process  --desc_path /tmp/foo.json   14.24s user 3.97s system 277% cpu 6.570 total
```

improve: speed up native EXIF parsing

---

mapillary_tools/geotag/geotag_videos_from_exiftool_video.py
mapillary_tools/geotag/geotag_videos_from_video.py
mapillary_tools/geotag/utils.py
mapillary_tools/process_sequence_properties.py
mapillary_tools/video_data_extraction/extract_video_data.py
tests/unit/test_sequence_processing.py

So all videos have a unified place to check stationary

refactor: move stationary check from geotagging to process_sequence_properties.py

---

mapillary_tools/geotag/geotag_from_generic.py
mapillary_tools/geotag/geotag_images_from_exif.py
mapillary_tools/geotag/geotag_images_from_exiftool.py
mapillary_tools/geotag/geotag_images_from_exiftool_both_image_and_video.py
mapillary_tools/geotag/geotag_images_from_gpx.py
mapillary_tools/geotag/geotag_images_from_gpx_file.py
mapillary_tools/geotag/geotag_images_from_video.py
mapillary_tools/geotag/geotag_videos_from_exiftool_video.py
mapillary_tools/geotag/geotag_videos_from_video.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/sample_video.py
mapillary_tools/types.py
mapillary_tools/utils.py
mapillary_tools/video_data_extraction/extract_video_data.py
mapillary_tools/video_data_extraction/extractors/exiftool_xml_parser.py

So we can unify `--geotag_source` and `--video_geotag_source` (in next PRs)

refactor: simplify geotagging

---

.github/workflows/python-package.yml
tests/cli/blackvue_parser.py
tests/cli/camm_parser.py
tests/cli/exif_read.py
tests/cli/gpmf_parser.py
tests/cli/simple_mp4_parser.py
tests/cli/upload_api_v4.py

Fix `tests/cli` which are useful for debugging issues

chore: fix test cli

---

mapillary_tools/types.py
mapillary_tools/upload.py
mapillary_tools/uploader.py
tests/unit/test_upload_api_v4.py
tests/unit/test_uploader.py

Adds `ZipImageSequence` to group all image zip related functions and expose 2 classmethods `zip_images` and `zip_sequence_fp`

refactor: upload zips

---

mapillary_tools/api_v4.py
mapillary_tools/authenticate.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
tests/cli/upload_api_v4.py
tests/unit/test_upload_api_v4.py
tests/unit/test_uploader.py

- reduce the usage of emitters which is hard to track
- add `upload_shifted_chunks()` in upload_api_v4.py to work better with progress bar
- Separate `Progress` events to `UploaderProgress` and `SequenecProgress`
- move `finish_upload` to api_v4.py because it's a GraphAPI call

refactor: improve uploader related modules

---

mapillary_tools/camm/camm_builder.py
mapillary_tools/constants.py
mapillary_tools/geotag/geotag_videos_from_video.py
mapillary_tools/history.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
tests/unit/test_camm_parser.py

General improvements on uploads and CAMM mp4 builder:
- CAMM builder now accepts `CAMMInfo` instead of `VideoMetadata` (reduce dependencies)
- Report progress every 10 seconds in verbose/debug mode, so less verbose
- Return filetype in error metadatas in all VideoExtractors, so videos can be correctly recognized in the process summery report
- Reset retries=0 when a chunk is successfully uploaded
- Move all envvars to `constants.py`

refactor: Improve uploader and CAMM mp4 builder

---

mapillary_tools/exceptions.py
mapillary_tools/mp4/io_utils.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/types.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
tests/unit/test_exceptions.py
tests/unit/test_upload_api_v4.py
tests/unit/test_uploader.py

Make sure certain errors (e.g. image file not found, invalid image EXIF, or invalid zipfile) do not fail the overall upload process. Instead, return the error and continue uploading. After all uploads are done, show the summary and list all upload errors.

improve: handle upload errors

---

mapillary_tools/commands/process.py
mapillary_tools/constants.py
mapillary_tools/exiftool_read.py
mapillary_tools/exiftool_runner.py
mapillary_tools/geotag/factory.py
mapillary_tools/geotag/geotag_images_from_exiftool.py
mapillary_tools/geotag/geotag_images_from_exiftool_both_image_and_video.py
mapillary_tools/geotag/geotag_images_from_gpx_file.py
mapillary_tools/geotag/geotag_images_from_nmea_file.py
mapillary_tools/geotag/geotag_videos_from_exiftool_video.py
mapillary_tools/geotag/geotag_videos_from_gpx.py
mapillary_tools/geotag/options.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/sample_video.py
mapillary_tools/types.py
mapillary_tools/video_data_extraction/extractors/exiftool_runtime_parser.py
tests/cli/exiftool_runner.py
tests/integration/fixtures.py
tests/integration/test_gopro.py
tests/integration/test_process.py

When running `process`, MT now defaults to using native parsers (exif, camm, gopro, blackvue) before falling back to ExifTool for any failures. This approach leverages our previous speedup work (https://github.com/mapillary/mapillary_tools/pull/722, https://github.com/mapillary/mapillary_tools/pull/729, https://github.com/mapillary/mapillary_tools/pull/731, https://github.com/mapillary/mapillary_tools/pull/721) making native parsing 3-10x faster while maintaining ExifTool's broad format support.
If ExifTool is not found, a warning is printed:
```
2025-03-31 20:08:05,510 - WARNING - Skip "exiftool_runtime" because: [Errno 2] No such file or directory: 'exiftool2'
```
You can specify the path to your ExifTool installation with the `MAPILLARY_TOOLS_EXIFTOOL_PATH` environment variable. When …

improve: geotag with exiftool after native geotagging

---

mapillary_tools/geotag/geotag_from_generic.py
mapillary_tools/gpmf/gpmf_parser.py

This is to distinguish GoPro and other cameras that using the same GPMD format.
If we can not find even a single `DEVC` in the "gpmd" container, we consider it not a GoPro video. Some cameras, .e.g. VANTRUE N2S 4K Dashcam, for example, do use "gpmd" description but they are not using the GPMF format.

fix: distinguish GoPro and other cameras using the same gpmd format

---

mapillary_tools/exiftool_runner.py

Just adding the -fast parameter for faster parsing.

Use -fast parameter when running exiftool

---

mapillary_tools/exiftool_read_video.py
mapillary_tools/upload.py
mapillary_tools/uploader.py
tests/integration/fixtures.py
tests/integration/test_process.py
tests/integration/test_process_and_upload.py
tests/integration/test_upload.py
tests/unit/test_uploader.py

Previously we used `sequence_md5sum` for both upload resuming and duplication check. However there is a tricky case where `MAPFilename` in image description changed -> the file content changed but `sequence_md5sum` remains same. So we can't use `sequence_md5sum` for resuming. Instead, we introduce `upload_md5sum` for resuming, while keeping using `sequence_md5sum` for duplication check.

fix: ensure session key unique to upload content

---

mapillary_tools/api_v4.py
mapillary_tools/constants.py
mapillary_tools/types.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
tests/integration/fixtures.py
tests/integration/test_gopro.py
tests/integration/test_history.py
tests/integration/test_process.py
tests/integration/test_process_and_upload.py
tests/integration/test_upload.py
tests/unit/test_upload_api_v4.py
tests/unit/test_uploader.py

Upload images file by file concurrently.
Benefits:
* No need to zip images (extra space and IO) and then upload
* Faster upload due to parallel uploading (see below)
* The offset reset issue is mitigated (for imagery uploading only) https://github.com/mapillary/mapillary_tools/issues/569
Before: single thread uploading a zipfile of 2GB images
```
2.00G/2.00G [02:21<00:00, 15.2MB/s]
```
Now: parallel uploading with 128 workers
```
2.00G/2.00G [00:52<00:00, 41.0MB/s]
```
Now: parallel uploading with 64 workers
```
2.00G/2.00G [00:50<00:00, 42.8MB/s]
```

feat: support uploading images file by file

---

mapillary_tools/blackvue_parser.py

900X contains `GNGGA`
```
python3 -m pytest mapillary_tools --doctest-modules
```

fix: blackvue 900x parsing

---

mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
tests/integration/fixtures.py
tests/unit/test_upload_api_v4.py

Do not write uploaded files into mapillary_public_uploads in current dir. Write them into the tempdir instead (and log the path)

refactor: improve upload service

---

mapillary_tools/upload.py

fix: progress bar was initialized twice

---

mapillary_tools/api_v4.py
mapillary_tools/constants.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
tests/unit/test_uploader.py

- **refactor: use UploadOptions**
- **estimate read timeouts**
- **fix tests**
- **log as json**

feat: upload timeouts

---

mapillary_tools/api_v4.py
mapillary_tools/authenticate.py
mapillary_tools/commands/upload.py
mapillary_tools/constants.py
mapillary_tools/http.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
tests/cli/upload_api_v4.py
tests/unit/test_upload_api_v4.py

This pull request refactors the API v4 authentication and HTTP request logic to streamline session management, improve code clarity, and make upload worker configuration more flexible. The main changes include replacing custom HTTP request handling with a shared `http.Session`, updating authentication flows to use session objects, and introducing a configurable number of upload workers.
**API and HTTP session refactoring:**
* Removed custom HTTP request functions and SSL adapter logic from `api_v4.py`, replacing them with new `create_user_session` and `create_client_session` helpers that return pre-configured `http.Session` objects for authenticated requests. All API methods now accept a session object instead of raw tokens. [[1]](diffhunk://#diff-31912c9803790ab2628fcd3fa9fba2976ca2e501f9 …

feat: upload images with keep-alive

---

mapillary_tools/geotag/video_extractors/gpx.py
tests/integration/test_process.py

This PR adds the missing filesize calculation to the GPX extractor so all videos processed by MT have a filesize.

Calculate video filesize when using gpx extractor

---

mapillary_tools/history.py
mapillary_tools/uploader.py
tests/unit/test_uploader.py

- **fix: race condition in image uploader and add tests**
- **Add tests for ImageSequenceUploader. Follow the following principles:**
- **I saw that you use multithreads in test_image_sequence_uploader_multithreading_with_cache_enabled. No need to do that because `sequence_uploader.upload_images` is using inside multithreading. We can guranteee that sequence_uploader.upload_images won't be called in multithreads**
- **Using cached_time to determine if it's cached is probably not reliable. Try mock some internal implementation, e.g. if single_image_uploader.cache.get() is called and filehandle if filehandle is cached there**
- **increase num_images**
- **Ok, it looks like it is hard to tests with the current implementation. Let's make some changes in uploader.py**
- **Ok now let's improve …

fix: race condition in image uploader

---

mapillary_tools/uploader.py

This pull request enhances the upload retry logic in `mapillary_tools/uploader.py` to handle rate-limiting and server errors more robustly. The main improvements include more precise parsing of HTTP response headers and error bodies to determine retryability and wait times, and refactoring the retry logic to support these changes.
**Retry Logic Improvements:**
* Refactored `_is_retriable_exception` to return a tuple `(retriable: bool, retry_after_sec: int)` instead of just a boolean, enabling more granular control over retry timing based on server responses and headers. Added comprehensive docstring and test examples.
* Added `_parse_backoff` and `_parse_retry_after_from_header` helpers to extract backoff durations from JSON responses and the `Retry-After` HTTP header, supporting both …

fix: handle HTTP 429 as retriable errors

---

mapillary_tools/exif_write.py
tests/unit/test_exifedit.py

Fixes something that has been bugging me for a long time: There is no need to limit Exif tag value precision.

Write fully reduced Exif rationals with full precision
