python/upload.py
python/upload_with_authentication.py

Make upload_with_authentication.py actually usable with real-life
sequence lengths and internet connections.

Upload retries with delay

---

python/README.md
python/lib_gps_exif.py
python/remove_duplicates.py

The code is now PEP008 compliant according to my PEP008 tool. One line is too long acording to the tool, but it would not make sense to split it up, so it is OK acording to the standard.
Also made the code work that warns if the mapper has gone to fast, e.g. from Russia to Denmark in 4 seconds or if a sequence should just be split.

PEP008 compliant

---

python/upload.py
python/upload_with_authentication.py

just a little more information for the user when is uploading photos.
ex:
…
Uploading: 20150917_130354a.jpg
Success: 20150917_130353.jpg
Uploading: 82%
Uploading: 20150917_130355.jpg
Success: 20150917_130354a.jpg
Uploading: 83%
Uploading: 20150917_130355a.jpg
Success: 20150917_130355.jpg
…

Show Percent when uploading

---

python/requirements.txt

Pillow 3.0.0 changes EXIF behavior significantly and is currently broken
Fixes #101

Use Pillow 2.9.0

---

python/README.md
python/download_images.py

Updated URLs because of new Mapillary website.
Fixed HTTP refused connection issue and enforcing HTTPS in download_images.py

Updated URLs

---

python/lib/exif.py

sub_sec should not be divided by 10⁶ since they ain’t microseconds, they are just the after dot digits

Fix subsec metadata conversion

---

mounts/gophone/phone_holder.scad

some variables assumed a portrait orientation, some a portrait orientation. Now all variables refer to portrait orientation, looking at the screen. Fixes https://github.com/mapillary/mapillary_tools/issues/96

fixing inconsistencies in variable names

---

python/README.md
python/download_images.py

Hi! This is not major, but just a little cleanup. Thanks so much for this repo, it's super helpful!
(Also, I'm new at github pull requests, so let me know if I'm doing anything wrong here.)
Thanks,
Dan

download_images: add image_size arg and use argparse to parse args

---

python/add_mapillary_tag_from_exif.py
python/add_mapillary_tag_from_json.py
python/upload_with_preprocessing.py

Fix broken comment in add_mapillary_tag_from_exif.py

add_mapillary_tag_from_exif.py: Fix comment

---

python/geotag_from_gpx.py

`exit_bearing` should be `corrected_bearing`

Use correct variable name

---

python/download_images.py

As it functions identically no need to update documentation
Fixes #187

Update download_images.py to use API V3

---

python/lib/geo.py

changing the function decimal_to_dms, since the output of current is not
ok for piexif. this function is only used in the exifedit class, can we merge this now, before merging the piexif stuff

feat: change decimal_to_dms

---

.dockerignore
.travis.yml
Dockerfile
README.md
python/requirements.txt
setup.cfg
tests/test_exifedit.py

@jernejaMislej @ybkuang Builds are run [here](https://travis-ci.org/mapillary/mapillary_tools/builds). 
I had to remove the `test` prefix from the helper methods because they are otherwise picked up and run as (failing) tests by Pytest.
For running locally in the same environment as during CI, use the docker commands under `before_install` and `script` directives in the `travis.yml` file.

Add continuous integration

---

python/json_to_gpx.py
python/lib/exifedit.py

the script is missing options to pass args for gpx trace file name, path
and then save it to file instead of printing it out.
also if the lat,lon or alt are not in json, which does actually happen,
the script will fail, so there is a check missing there

feat: several missing features in the script

---

python/README.md

Propose fix two typos

---

bin/edit_config.py
mapillary_tools/commands/video_process.py
mapillary_tools/processing.py
mapillary_tools/uploader.py

partial merge to fix issues with aws keys

Add update config command

---

mapillary_tools/uploader.py

I fixed handling of multi-byte (non-ASCII) user name.
Related #281

fixed issue #281

---

mapillary_tools/gpx_from_blackvue.py
mapillary_tools/interpolation.py
mapillary_tools/process_csv.py
mapillary_tools/processing.py
mapillary_tools/upload.py
mapillary_tools/uploader.py

Reference issue: mapillary/mapillary_elva#5349
@jernejaMislej there is still an issue that I'd like to get your input
For example, an scenario where images do not have EXIF for geotag but somewhere there is a `.gpx` file, so
Given that the images do not have EXIF to geotag
When the user executes `mapillary_tools process --import_path ...`
Then
- Actual, the process exit with status code 0
- Expected, the process exit with status code 1
Shall we invoke `sys.exit(1)` as soon as there is not info to geotag in https://github.com/mapillary/mapillary_tools/blob/master/mapillary_tools/processing.py#L105?
Do you have any recommendation for other `process_*` steps in the pipeline?
This is a minified console output
```
Running user_process for 0 images, skipping 15 images.
No images to run user …
```

feat: update error exit code

---

mapillary_tools/error.py
mapillary_tools/exif_write.py
mapillary_tools/insert_MAPJson.py
mapillary_tools/interpolation.py
mapillary_tools/ipc.py
mapillary_tools/post_process.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/process_import_meta_properties.py
mapillary_tools/process_sequence_properties.py
mapillary_tools/process_upload_params.py
mapillary_tools/process_user_properties.py
mapillary_tools/processing.py
mapillary_tools/upload.py
mapillary_tools/uploader.py

add error module to print and send ipc error messages
Reference issue: mapillary/mapillary_elva#6209

feat: add ipc module to send messages to a parent process

---

README.md

Adding links to Mapillary Tools package. Revising installation section to become "Custom Installation".

Update README.md with Mapillary Tool Packages

---

mapillary_tools/ipc.py
mapillary_tools/post_process.py

@josealb @jernejaMislej Could you create a patch release with this PR?

Fix ipc exif encoding

---

mapillary_tools/uploader.py
setup.py

Signed-off-by: Francois Gouget <fgouget@free.fr>

yaml is not used anymore.

---

README.md

This includes instructions for installing mapillary_tools on an Android device, without root privileges. I've used mapillary_tools like this to successfully submit nearly 100k images.

Update README.me with Android install instructions

---

mapillary_tools/api_v3.py
mapillary_tools/edit_config.py
mapillary_tools/login.py
mapillary_tools/process_upload_params.py
mapillary_tools/processing.py
mapillary_tools/uploader.py

When you input wrong or invalid user crendentials it will prompt again

Improve login error handling

---

mapillary_tools/process_csv.py

Fixed the bug introduced in https://github.com/mapillary/mapillary_tools/pull/400.
Columns the user specified could be None

fix columns that contains None

---

mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py

Fixes https://github.com/mapillary/mapillary_tools/issues/405

generate zip file as tempfile and remove failed_file_list

---

mapillary_tools/commands/process_and_upload.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
requirements.txt

- Fix the potential timeout error (403) for large uploads
- The next time when you upload the same file (packed zip file), it will resume from the last failure.\
- Add back the upload progress bar
Fixes https://github.com/mapillary/mapillary_tools/issues/405 and https://github.com/mapillary/mapillary_tools/issues/410

support resumable upload

---

mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py

Fixes https://github.com/mapillary/mapillary_tools/issues/419

catch retryable errors and retry for 10 times

---

mapillary_tools/ffmpeg.py
mapillary_tools/ffprobe.py
mapillary_tools/processing.py

Fixes https://github.com/mapillary/mapillary_tools/issues/391 and https://github.com/mapillary/mapillary_tools/issues/394

Imporove error message

---

mapillary_tools/ffmpeg.py
mapillary_tools/gpmf.py
mapillary_tools/gpx_from_gopro.py
mapillary_tools/processing.py

Fixes https://github.com/mapillary/mapillary_tools/issues/413

fix gpx extraction for gopro

---

mapillary_tools/exif_read.py
mapillary_tools/ffmpeg.py
mapillary_tools/ffprobe.py
mapillary_tools/geo.py
mapillary_tools/gps_parser.py
mapillary_tools/process_video.py
mapillary_tools/processing.py

Fixes https://github.com/mapillary/mapillary_tools/issues/424
Two issues here:
1. the ffprobe.py module does not parse ffprobe output correctly. This PR use `-print_format=json` to fix that.
2. video time not in the scope of GPX file. It's likely to be timezone parsing incorrectly.

fix: ffprobe parsing

---

mapillary_tools/insert_MAPJson.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/process_import_meta_properties.py
mapillary_tools/process_sequence_properties.py
mapillary_tools/process_upload_params.py
mapillary_tools/process_user_properties.py
mapillary_tools/processing.py
mapillary_tools/uploader.py

refactor supported file types

---

mapillary_tools/process_user_properties.py

This PR removes logging organization description as it's optional.

Fix organization processing

---

mapillary_tools/types.py
mapillary_tools/upload.py
mapillary_tools/upload_api_v4.py
mapillary_tools/uploader.py
mapillary_tools/utils.py
schema/image_description_schema.json
tests/integration/test_process.py
tests/unit/test_uploader.py

- Dismiss the image_dir parameter
- Add md5sum per image and calculate the sequence md5 for duplication check
- Test the upload API

MD5sum check before upload

---

mapillary_tools/ipc.py
mapillary_tools/upload.py

- JSON serialize IPC payload early
- Use entity_size - first_offset to calculate uploaded sizes

Fix JSON serilization before IPC sending

---

mapillary_tools/geotag/geotag_from_blackvue.py

Fix no error descs written for blackvue geotagging

---

mapillary_tools/ffmpeg.py
mapillary_tools/sample_video.py

Fixes https://github.com/mapillary/mapillary_tools/issues/465

Hide banner in ffmpeg and ffprobe

---

mapillary_tools/sample_video.py

Fixes https://github.com/mapillary/mapillary_tools/issues/473

Fix video start time for multiple videos

---

mapillary_tools/upload.py

Fixes https://github.com/mapillary/mapillary_tools/issues/477

Show progress bar for uploading

---

mapillary_tools/geotag/geotag_from_blackvue.py
mapillary_tools/geotag/geotag_from_gopro.py
mapillary_tools/image_log.py
mapillary_tools/process_geotag_properties.py
tests/unit/test_utils.py

Fixes https://github.com/mapillary/mapillary_tools/issues/478

Process only specified video sample images in video_process

---

README.md
mapillary_tools/__main__.py
mapillary_tools/commands/upload.py
mapillary_tools/upload.py

- Support upload multiple files at once
- Update README

Feature: support uploading multiple files/directories at once

---

mapillary_tools/__main__.py
mapillary_tools/error.py
mapillary_tools/geo.py
mapillary_tools/geotag/geotag_from_blackvue.py
mapillary_tools/geotag/geotag_from_exif.py
mapillary_tools/geotag/geotag_from_generic.py
mapillary_tools/geotag/geotag_from_gopro.py
mapillary_tools/geotag/geotag_from_gpx.py
mapillary_tools/geotag/geotag_from_gpx_file.py
mapillary_tools/geotag/geotag_from_nmea_file.py
mapillary_tools/geotag/utils.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/sample_video.py

Show progress bars which is useful for processing large amount of files

Add progress bars for processing

---

mapillary_tools/error.py
mapillary_tools/geotag/geotag_from_blackvue.py
mapillary_tools/geotag/geotag_from_gpx.py
mapillary_tools/upload.py
tests/integration/test_process.py

Verify that it's a valid blackvue and it's not stationary﻿

Validate BlackVue videos before uploading

---

mapillary_tools/exif_write.py

Piexif ﻿validates tags when dump EXIF data, and throw errors on invalid tags. This PR deletes invalid tags before dumping.
Fixes https://github.com/mapillary/mapillary_tools/issues/482

Fix: delete invalid tags before writing exif

---

mapillary_tools/exif_read.py
mapillary_tools/geotag/geotag_from_exif.py
tests/unit/test_exifedit.py

- Write MAPAltitude in image description. Fixes https://github.com/mapillary/mapillary_tools/issues/412
- Return None instead of 0, if the rational denominator is 0 when reading float values, e.g. GPS, directions, etc.
- Fix GoPro HERO 9 subseconds reading. Fixes https://github.com/mapillary/mapillary_tools/issues/388

EXIF read related fixes

---

tests/cli/gpmf_parser.py
tests/cli/gps_filter.py
tests/unit/test_gps_filter.py

```
python3 -m tests.cli.gpmf_parser ~/Downloads/MyGoProVideos/ > ~/Downloads/MyGoProVideos/ALL.gpx
python3 -m tests.cli.gps_filter < ~/Downloads/MyGoProVideos/ALL.gpx
```

feat: move GPS filter out as a separate CLI

---

mapillary_tools/geotag/simple_mp4_parser.py
mapillary_tools/geotag/utils.py
tests/cli/camm_parser.py

Fixes https://github.com/mapillary/mapillary_tools/issues/536

fix: sample sizes and sample deltas not equal length

---

mapillary_tools/commands/__main__.py
mapillary_tools/commands/process.py
mapillary_tools/commands/sample_video.py
mapillary_tools/commands/upload.py
mapillary_tools/commands/upload_blackvue.py
mapillary_tools/commands/upload_zip.py
mapillary_tools/commands/zip.py
mapillary_tools/geotag/geotag_from_blackvue.py
mapillary_tools/geotag/geotag_from_camm.py
mapillary_tools/geotag/geotag_from_exif.py
mapillary_tools/geotag/geotag_from_gopro.py
mapillary_tools/geotag/geotag_from_gpx.py
mapillary_tools/geotag/geotag_from_gpx_file.py
mapillary_tools/geotag/geotag_from_nmea_file.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/process_import_meta_properties.py
mapillary_tools/sample_video.py
mapillary_tools/types.py
mapillary_tools/upload.py
mapillary_tools/uploader.py
mapillary_tools/utils.py
mypy.ini
tests/integration/test_gopro.py
tests/unit/generate_test_image.py
tests/unit/test_config.py
tests/unit/test_geo.py
tests/unit/test_sample_video.py
tests/unit/test_uploader.py
tests/unit/test_utils.py

- replace string path with pathlib.Path
- fix tests and types

refactor: use pathlib

---

mapillary_tools/ffmpeg.py
pyinstaller/main.py
tests/integration/test_gopro.py
tests/integration/test_process.py

Fixes https://github.com/mapillary/mapillary_tools/issues/547

fix: multiprocessing spawn warnings from pyinstaller

---

mapillary_tools/upload_api_v4.py
tests/cli/upload_api_v4.py

- refactor: log request&resp in upload api for debugging
- move the main module to tests.cli

refactor: improve upload API logging

---

mapillary_tools/__init__.py
mapillary_tools/uploader.py

For debugging https://github.com/mapillary/mapillary_tools/issues/569

fix: stop uploading if the server offset does not move as expected

---

mapillary_tools/geotag/blackvue_parser.py
mapillary_tools/geotag/camm_builder.py
mapillary_tools/geotag/camm_parser.py
mapillary_tools/geotag/geotag_from_blackvue.py
mapillary_tools/geotag/gpmf_parser.py
mapillary_tools/geotag/simple_mp4_parser.py
mapillary_tools/geotag/utils.py
mapillary_tools/upload.py
tests/cli/blackvue_parser.py
tests/cli/upload_api_v4.py
tests/unit/test_camm_parser.py

- feat: put make and model in VideoMetadata
- rename extract_points to extract_video_metadata
- fix tests
;)

feat: write make/model in CAMM videos

---

mapillary_tools/commands/__main__.py
mapillary_tools/upload.py
tests/unit/test_uploader.py

- write mapillary_tools version in debug logs and upload history
- shorten import_paths in logs

feat: log mapillary_tools version

---

mapillary_tools/commands/process_and_upload.py
mapillary_tools/commands/sample_video.py
mapillary_tools/commands/video_process.py
mapillary_tools/commands/video_process_and_upload.py
mapillary_tools/constants.py
mapillary_tools/exif_read.py
mapillary_tools/exif_write.py
mapillary_tools/ffmpeg.py
mapillary_tools/geo.py
mapillary_tools/geotag/construct_mp4_parser.py
mapillary_tools/geotag/geotag_from_exif.py
mapillary_tools/geotag/geotag_from_gpx.py
mapillary_tools/geotag/geotag_from_gpx_file.py
mapillary_tools/geotag/mp4_sample_parser.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/sample_video.py
mapillary_tools/upload.py
tests/cli/exif_read.py
tests/cli/simple_mp4_parser.py
tests/cli/upload_api_v4.py
tests/integration/fixtures.py
tests/integration/test_gopro.py
tests/integration/test_process.py
tests/unit/test_exifedit.py
tests/unit/test_exifread.py
tests/unit/test_geo.py
tests/unit/test_mp4_sample_parser.py
tests/unit/test_sample_video.py

- refactor process_video
- add exif_write.add_make and add_model
- add Interpolator
- add MovieBoxParser and TrackBoxParser
- add Probe that parse probe output from ffprobe
- add sample_video_by_distance
- add --video_sample_distance and default it to 5 meters
- fix tests
- test Interpolator
- filter out samples outside the GPS track

feat: sample by minimal distance 5 meters

---

mapillary_tools/ffmpeg.py
mapillary_tools/sample_video.py

Fixes https://github.com/mapillary/mapillary_tools/issues/600

fix: large ffmpeg argument

---

tests/integration/test_gopro.py
tests/integration/test_process.py

Fixes https://github.com/mapillary/mapillary_tools/issues/597

fix: path assertion for windows in tests

---

.github/workflows/python-package.yml
mapillary_tools/ffmpeg.py

- Fixes https://github.com/mapillary/mapillary_tools/issues/600 for windows
- Also set up ffmpeg so we can test them for all platforms

chore: set up ffmpeg in GitHub Actions

---

mapillary_tools/api_v4.py
mapillary_tools/exceptions.py
mapillary_tools/upload.py

Fixes https://github.com/mapillary/mapillary_tools/issues/598

improve: add exit codes for upload connection/timeout/HTTPauthorization errors respectively

---

mapillary_tools/exif_read.py
tests/integration/test_process.py
tests/integration/test_process_and_upload.py
tests/unit/test_exifread.py

Fixes https://github.com/mapillary/mapillary_tools/issues/481

improve: prefer GPS DateTime over DateTimeOriginal

---

mapillary_tools/exceptions.py
mapillary_tools/history.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/types.py
mapillary_tools/upload.py
mapillary_tools/uploader.py
tests/integration/test_history.py
tests/unit/test_exceptions.py
tests/unit/test_sequence_processing.py

- refactor: move types.group_and_sort_images
- move history related functions to history.py

feat: add upload status in mapillary_image_description.json

---

mapillary_tools/commands/process.py
mapillary_tools/exceptions.py
mapillary_tools/exiftool_read_video.py
mapillary_tools/geotag/geotag_from_exif.py
mapillary_tools/geotag/geotag_from_exiftool.py
mapillary_tools/geotag/geotag_from_exiftool_video.py
mapillary_tools/geotag/geotag_from_generic.py
mapillary_tools/geotag/geotag_from_gpx.py
mapillary_tools/geotag/geotag_from_video.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/types.py
mapillary_tools/utils.py
schema/image_description_schema.json
tests/unit/test_sequence_processing.py

- chore: remove logs
- feat: add geotag_source exiftool
https://github.com/mapillary/mapillary_tools/issues/619

feat: geotag from exiftool (for both images and videos)

---

mapillary_tools/__init__.py
mapillary_tools/geotag/geotag_images_from_exiftool.py
mapillary_tools/geotag/geotag_images_from_exiftool_both_image_and_video.py
mapillary_tools/geotag/geotag_images_from_video.py
mapillary_tools/geotag/geotag_videos_from_exiftool_video.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/sample_video.py

- feat: support exiftool in video_process
- some comments

feat: support local video process from exiftool

---

mapillary_tools/commands/process.py
mapillary_tools/exceptions.py
mapillary_tools/geotag/geotag_images_from_exif.py
mapillary_tools/geotag/geotag_images_from_exiftool.py
mapillary_tools/geotag/geotag_images_from_exiftool_both_image_and_video.py
mapillary_tools/geotag/geotag_images_from_gpx.py
mapillary_tools/geotag/geotag_images_from_gpx_file.py
mapillary_tools/geotag/geotag_images_from_nmea_file.py
mapillary_tools/geotag/geotag_images_from_video.py
mapillary_tools/geotag/geotag_videos_from_exiftool_video.py
mapillary_tools/geotag/geotag_videos_from_video.py
mapillary_tools/process_geotag_properties.py
mapillary_tools/types.py
tests/unit/test_description.py
tests/unit/test_sequence_processing.py

- add --num_processes
- multiprocessing metadata validation
- refactor
- add MapillaryMetadataValidationError
- fix the multiprocessing serialization

feat: add cli param --num_processes

---

.github/workflows/python-package.yml
.github/workflows/release.yml

- **upgrade pypa to latest**
- **update ffmpeg action**

CI: upgrade actions

---

.github/workflows/release.yml
mapillary_tools/__init__.py

Added builds for macOS ARM and ubuntu ARM

CI: support more CPU architectures

---

mapillary_tools/process_sequence_properties.py
tests/unit/test_sequence_processing.py

- Refactored `process_sequence_properties` to be more readable
- Added a few AI-generated tests

improve: add tests for sequence processing

---

mapillary_tools/geotag/geotag_videos_from_video.py
mapillary_tools/geotag/gpmf_parser.py
mapillary_tools/upload.py
mapillary_tools/video_data_extraction/extractors/gopro_parser.py

Dataset:
```
❯ du -sh ~/Downloads/MyGoProVideos                              
55G	~/Downloads/MyGoProVideos
```
Before:
```
❯ uv run -m mapillary_tools.commands --verbose process ~/Downloads/MyGoProVideos --desc_path /tmp/foo.json --skip_process_errors                                   
2025-03-19 15:17:56,729 - DEBUG   - CLI param: duplicate_angle: 5.0
2025-03-19 15:18:30,317 - INFO    - Found 27 videos and 1 errors after video limit checks
2025-03-19 15:18:30,318 - DEBUG   - Validating 51 metadatas
2025-03-19 15:18:31,449 - INFO    - Check the description file for details: /tmp/foo.json
2025-03-19 15:18:31,453 - INFO    -       51 gopro(s) read in total
2025-03-19 15:18:31,453 - INFO    -            27 gopro(s) (41813.7 MB) are ready to be uploaded
2025-03-19 15:18:31,453 - WARNING - …
```

improve: speed up GoPro processing
